import * as XLSX from 'xlsx';
import type { AppData, WorkClass, Trabajo, RouteKey } from '../types';
import { emptyData, INFRA } from './mockData';
export const norm = (v:any)=>String(v??'').normalize('NFD').replace(/[̀-ͯ]/g,'').trim().toUpperCase();
export const clean = (v:any)=>String(v??'').replace(/_x000D_/g,'').trim();
export function num(v:any){ if(typeof v==='number') return Number.isFinite(v)?v:NaN; let s=String(v??'').trim().toUpperCase().replace(/KM/g,'').replace(/\s/g,''); const m=s.match(/(-?\d+(?:[\.,]\d+)?)\+(\d{1,3})/); if(m) return parseFloat(m[1].replace(',','.'))+parseFloat(m[2].padEnd(3,'0'))/1000; s=s.replace(',','.').replace(/[^0-9.\-]/g,''); const p=s.split('.'); if(p.length>2) s=p[0]+'.'+p.slice(1).join(''); const n=parseFloat(s); return Number.isFinite(n)?n:NaN; }
export const routeOf = (v:any):RouteKey => { const s=norm(v); return (s.includes('ASS')||s.includes('ACCESO SUR')||s.includes('TUNEL'))?'ASS':'R5'; };
const pad=(n:any)=>String(n).padStart(2,'0');
function fmtHora(v:any){ if(v==null||v==='') return ''; if(v instanceof Date&&!isNaN(+v)) return pad(v.getHours())+':'+pad(v.getMinutes()); if(typeof v==='number'&&Number.isFinite(v)){const f=((v%1)+1)%1,tm=Math.round(f*24*60),h=Math.floor(tm/60)%24,m=tm%60; return pad(h)+':'+pad(m)} const s=String(v).trim(),m=s.match(/(?:\d{1,2}\/\d{1,2}\/\d{2,4}\s+)?(\d{1,2}):(\d{2})(?::\d{2})?/); return m?pad(m[1])+':'+m[2]:s; }
function rows(wb:XLSX.WorkBook, sh:string){ return XLSX.utils.sheet_to_json<any[]>(wb.Sheets[sh],{header:1,defval:'',blankrows:false}); }
function findHeader(rs:any[][], need:string[]){ for(let i=0;i<Math.min(rs.length,12);i++){ const line=rs[i].map(norm).join('|'); if(need.every(n=>line.includes(n))) return {row:i}; } return null; }
function mapHeaders(row:any[], preferFrom=0){ const cols:any={}; row.forEach((v,i)=>{ const h=norm(v); if(!h||i<preferFrom) return; if(h.includes('RUTA')) cols.ruta ??= i; else if(h.includes('FECHA')) cols.fecha ??= i; else if(h.includes('RESPONSABLE')) cols.responsable=i; else if(h.includes('TIPO DE TRABAJOS')||h==='ACTIVIDAD') cols.trabajo ??= i; else if(h.includes('CONTRATISTA')) cols.contratista=i; else if(h.includes('KM INICIAL')) cols.kmInicial ??= i; else if(h.includes('KM FINAL')) cols.kmFinal ??= i; else if(h.includes('LONGITUD')) cols.longitud=i; else if(h.includes('PISTA')) cols.pistas ??= i; else if(h.includes('CALZADA')) cols.calzada=i; else if(h.includes('SECTOR')) cols.sector=i; else if(h.includes('HORARIO')) cols.horario=i; else if(h.includes('HORA INICIO')) cols.horaInicio=i; else if(h.includes('HORA FINAL')) cols.horaFinal=i; else if(h.includes('OBSERVACION')) cols.observacion=i; }); return cols; }
const val=(r:any[],i:any)=>i==null?'':clean(r[i]);
function workObj(tipo:WorkClass,r:any[],c:any,trabajo:string,k1:number,k2:number,km:number):Trabajo{ const ruta=tipo==='Día'?(val(r,c.rutaPanel)||val(r,c.ruta)||val(r,1)):val(r,c.ruta); const route=routeOf(ruta); return {tipo,nombre:trabajo,trabajo,km,ruta,route,fecha:val(r,c.fecha)||val(r,c.fechaPanel),responsable:val(r,c.responsable),contratista:val(r,c.contratista),kmInicial:k1,kmFinal:k2,longitud:val(r,c.longitud),pistas:val(r,c.pistas),calzada:val(r,c.calzada),sector:val(r,c.sector),horario:val(r,c.horario),horaInicio:fmtHora(r[c.horaInicio]),horaFinal:fmtHora(r[c.horaFinal]),observacion:val(r,c.observacion),estadoManual:'Programado',horaInicioReal:'',horaTerminoReal:''}; }
export async function parseWorkbookFile(file:File, base:AppData, kind:'classes'|'works'){ const buf=await file.arrayBuffer(); const wb=XLSX.read(buf,{type:'array',cellDates:true}); const next:AppData = { ...base, Troncal:[...base.Troncal], Enlace:[...base.Enlace], Pasarela:[...base.Pasarela], PMV:[...base.PMV], 'Peaje lateral':[...base['Peaje lateral']], Noche:[...base.Noche], Día:[...base.Día]}; let total=0; if(kind==='classes'){ INFRA.forEach(c=>{(next as any)[c]=[]}); let matchedSheets=0; wb.SheetNames.forEach(sh=>{ const cls=(INFRA as readonly string[]).find(c=>norm(c)===norm(sh)); if(!cls) return; matchedSheets++; rows(wb,sh).slice(1).forEach(r=>{ const nombre=clean(r[0]), km=num(r[1]), ruta=clean(r[2]); if(nombre&&Number.isFinite(km)&&km>=0&&km<=219){ (next as any)[cls].push({nombre,km,ruta,route:routeOf(ruta)}); total++; } }); }); if(matchedSheets===0) throw new Error('No se encontraron hojas de CLASES válidas (Troncal, Enlace, Pasarela, PMV, Peaje lateral).'); } else { next.Noche=[]; next.Día=[]; const map:any={}; wb.SheetNames.forEach(s=>map[norm(s)]=s); const load=(tipo:WorkClass)=>{ const name=tipo==='Noche'?map.NOCHE:(map.DIA||map['DÍA']); if(!name) return false; const rs=rows(wb,name); const hdr=findHeader(rs,['TIPO DE TRABAJOS','CONTRATISTA','KM INICIAL','HORA INICIO','RESPONSABLE']); let cols:any,start=4; if(hdr){ cols= tipo==='Día'?{...mapHeaders(rs[hdr.row],11),rutaPanel:mapHeaders(rs[hdr.row],0).ruta,fechaPanel:mapHeaders(rs[hdr.row],0).fecha}:mapHeaders(rs[hdr.row]); start=hdr.row+1; } else cols= tipo==='Día'?{rutaPanel:1,fechaPanel:2,ruta:1,fecha:2,trabajo:4,kmInicial:5,kmFinal:6,pistas:7,calzada:8,sector:9}:{ruta:1,responsable:3,trabajo:4,contratista:5,kmInicial:6,kmFinal:7,longitud:8,pistas:9,calzada:10,sector:11,horario:12,horaInicio:13,horaFinal:14,fecha:15,observacion:16}; rs.slice(start).forEach(r=>{ const trabajo=clean(r[cols.trabajo]), k1=num(r[cols.kmInicial]), k2=num(r[cols.kmFinal]), km=(k1+k2)/2; if(trabajo&&Number.isFinite(km)&&km>=0&&km<=219){ (next as any)[tipo].push(workObj(tipo,r,cols,trabajo,k1,k2,km)); total++; } }); return true; }; const loadedNight=load('Noche'); const loadedDay=load('Día'); if(!loadedNight&&!loadedDay) throw new Error('No se encontraron hojas de TRABAJOS válidas (NOCHE y/o DÍA).'); } return {data:next,total}; }
export async function fetchWeatherAt(lat:number,lon:number){ const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat.toFixed(4)}&longitude=${lon.toFixed(4)}&current=temperature_2m,wind_speed_10m,weather_code,is_day&timezone=auto&forecast_days=1`; try{ const r=await fetch(u); if(!r.ok) throw new Error('weather'); const j=await r.json(); const c=j.current; const codes:any={0:'Despejado',1:'Mayormente despejado',2:'Parcialmente nublado',3:'Nublado',45:'Neblina',48:'Neblina con escarcha',51:'Llovizna ligera',53:'Llovizna',55:'Llovizna intensa',61:'Lluvia ligera',63:'Lluvia',65:'Lluvia intensa',71:'Nieve ligera',73:'Nieve',75:'Nieve intensa',80:'Chubascos ligeros',81:'Chubascos',82:'Chubascos intensos',95:'Tormenta'}; return `${codes[c.weather_code]||'Condiciones variables'} · ${Math.round(c.temperature_2m)}°C · viento ${Math.round(c.wind_speed_10m)} km/h`; }catch{return 'Clima no disponible';} }
