import { useEffect, useMemo, useRef, useState } from 'react';
import type { AppData, LayerKey, Trabajo } from '../types';
import { CFG, COLORS, CURVES, INFRA, REGION_POINTS, RIVER_CROSSINGS, WORKS } from '../services/mockData';
import { fetchWeatherAt } from '../services/api';
const fmtKm=(k:number)=>Number(k).toLocaleString('es-CL',{maximumFractionDigits:3});
const title=(v:string)=>String(v||'').split(/[(),;.]/)[0].trim()||v;
const pad=(n:number)=>String(n).padStart(2,'0');
function now(){const d=new Date(); return `${pad(d.getDate())}-${pad(d.getMonth()+1)}-${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`}
function clamp(v:number,a:number,b:number){return Math.min(b,Math.max(a,v))}
export default function RouteCanvas({data,visible,setData}:{data:AppData; visible:Record<LayerKey,boolean>; setData:(d:AppData)=>void}){
 const ref=useRef<HTMLCanvasElement>(null); const tip=useRef<HTMLDivElement>(null); const [s,setS]=useState({z:1,pan:0,text:14,drag:false,lastX:0}); const hits=useRef<any[]>([]); const weather=useRef<Record<string,string>>({});
 const width=()=>innerWidth*.86, left=()=>innerWidth*.07, yR5=()=>innerHeight*.70, yASS=()=>innerHeight*.33, xWorld=(k:number)=>left()+((k-CFG.kmMin)/(CFG.kmMax-CFG.kmMin))*width(), xScreen=(k:number)=>xWorld(k)*s.z+s.pan, yRoute=(r:string)=>r==='ASS'?yASS():yR5();
 const routeVisible=(route:string,km:number)=>route==='ASS'?km>=CFG.assMin&&km<=CFG.assConnectEnd:km>=CFG.r5Min&&km<=CFG.r5Max;
 const setWorkState=(work:Trabajo)=>{ const states:any=['Programado','En ejecución','Terminado']; const next=states[(states.indexOf(work.estadoManual)+1)%3]; const copy:any={...data, Noche:[...data.Noche], Día:[...data.Día]}; const arr=copy[work.tipo] as Trabajo[]; const idx=arr.indexOf(work); const t={...work,estadoManual:next}; if(next==='En ejecución'&&!t.horaInicioReal)t.horaInicioReal=now(); if(work.estadoManual==='En ejecución'&&next==='Terminado')t.horaTerminoReal=now(); arr[idx]=t; setData(copy); };
 const draw=()=>{ const c=ref.current; if(!c)return; const dpr=Math.max(1,devicePixelRatio||1); c.width=Math.round(innerWidth*dpr); c.height=Math.round(innerHeight*dpr); c.style.width=innerWidth+'px'; c.style.height=innerHeight+'px'; const ctx=c.getContext('2d')!; ctx.setTransform(dpr,0,0,dpr,0,0); ctx.clearRect(0,0,innerWidth,innerHeight); hits.current=[];
  ctx.lineCap='round'; ctx.lineJoin='round'; ctx.strokeStyle='rgba(255,255,255,.96)'; ctx.lineWidth=4; ctx.beginPath(); ctx.moveTo(xScreen(CFG.r5Min),yR5()); ctx.lineTo(xScreen(CFG.r5Max),yR5()); ctx.stroke(); ctx.beginPath(); ctx.moveTo(xScreen(CFG.assMin),yASS()); ctx.lineTo(xScreen(CFG.assLineEnd),yASS()); ctx.stroke(); ctx.beginPath(); const x1=xScreen(CFG.assLineEnd),x2=xScreen(CFG.assConnectEnd); ctx.moveTo(x1,yASS()); ctx.bezierCurveTo(x1+(x2-x1)*.22,yASS(),x1+(x2-x1)*.78,yR5(),x2,yR5()); ctx.stroke();
  Object.entries(CURVES).forEach(([route, arr])=>{ctx.strokeStyle='#ffd600';ctx.lineWidth=5;(arr as any[]).forEach((cv,i)=>{let ini=Math.max(route==='ASS'?CFG.assMin:CFG.r5Min,Math.min(cv.ini,cv.fin)),fin=Math.min(route==='ASS'?CFG.assConnectEnd:CFG.r5Max,Math.max(cv.ini,cv.fin)); if(fin<ini)return; let mid=(ini+fin)/2,amp=(i%2===0?-1:1)*Math.min(10,Math.max(4,(fin-ini)*9)); ctx.beginPath();ctx.moveTo(xScreen(ini),yRoute(route));ctx.quadraticCurveTo(xScreen(mid),yRoute(route)+amp,xScreen(fin),yRoute(route));ctx.stroke();});});
  const tick=(route:string)=>{let y=yRoute(route),min=route==='ASS'?CFG.assMin:CFG.r5Min,max=route==='ASS'?CFG.assConnectEnd:CFG.r5Max,step=s.z>=7?1:s.z>=3?5:10,label=s.z>=7?5:10; ctx.textAlign='center';ctx.textBaseline='top';ctx.font=`700 ${s.text}px Segoe UI,Arial`; for(let km=Math.ceil(min/step)*step;km<=max+.001;km+=step){let x=xScreen(km),major=km%10===0||Math.abs(km-min)<.001,h=major?22:12;ctx.strokeStyle=`rgba(255,255,255,${major ? .95 : .35})`;ctx.lineWidth=major?1.8:1;ctx.beginPath();ctx.moveTo(x,y-h/2);ctx.lineTo(x,y+h/2);ctx.stroke(); if(km%label===0||Math.abs(km-min)<.001||Math.abs(km-max)<.001){ctx.fillStyle='rgba(255,255,255,.92)';ctx.fillText(`km ${fmtKm(km)}`,x,y+18)}}}; tick('R5'); tick('ASS');
  ctx.font=`900 ${s.text+2}px Segoe UI,Arial`;ctx.fillStyle='rgba(255,255,255,.72)';ctx.textAlign='left';ctx.fillText('ACCESO SUR A SANTIAGO',xScreen(CFG.assMin),yASS()-38);ctx.fillText('RUTA 5 SUR',xScreen(CFG.r5Min),yR5()-38);
  RIVER_CROSSINGS.forEach(r=>{if(!routeVisible(r.routeKey,r.km))return; let x=xScreen(r.km),y=yRoute(r.routeKey);ctx.strokeStyle='rgba(56,189,248,.92)';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,y-18);ctx.lineTo(x,y+18);ctx.stroke();ctx.font=`900 ${Math.max(10,s.text-2)}px Segoe UI Emoji`;ctx.textAlign='center';ctx.fillStyle='white';ctx.fillText('🌊',x,y-24);hits.current.push({type:'river',x,y,r:14,data:r});});
  REGION_POINTS.forEach((p,i)=>{const route=p.lat>-33.7?'ASS':'R5', km= route==='ASS'?Math.min(43.5,Math.max(0,(p.lat+33.617)/.084*43.5)):Math.min(219,Math.max(29,29+(-33.612-p.lat)/1.818*190)); if(!routeVisible(route,km))return; const key='R'+i; if(!weather.current[key]) fetchWeatherAt(p.lat,p.lon).then(t=>{weather.current[key]=t; draw()}); const txt=weather.current[key]||''; const emoji=/Lluvia|Chubascos|Llovizna|Tormenta/.test(txt)?'🌧️':/Nieve/.test(txt)?'🌨️':/Neblina/.test(txt)?'🌫️':/Nublado/.test(txt)?'☁️':'⛅️'; let x=xScreen(km),y=yRoute(route)-24; ctx.font='20px Segoe UI Emoji';ctx.textAlign='center';ctx.fillText(emoji,x,y);hits.current.push({type:'climate',x,y,r:14,data:{nombre:p.name,route,km,txt}})});
  const drawRot=(txt:string,x:number,y:number,color:string,align:CanvasTextAlign)=>{ctx.save();ctx.translate(x,y);ctx.rotate(-Math.PI/4);ctx.fillStyle=color;ctx.font=`800 ${s.text}px Segoe UI,Arial`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.shadowColor='rgba(0,0,0,.45)';ctx.shadowBlur=4;ctx.fillText(txt.toUpperCase(),0,0);ctx.restore();};
  INFRA.forEach(cls=>{ if(!visible[cls])return; data[cls].forEach((p,i)=>{ if(!routeVisible(p.route,p.km))return; let x=xScreen(p.km),y=yRoute(p.route); ctx.strokeStyle=COLORS[cls];ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y+9);ctx.lineTo(x,y+72);ctx.stroke(); drawRot(p.nombre,x,y+87,COLORS[cls],'right'); hits.current.push({type:'infra',cls,x,y:y+35,r:12,data:p}); }); });
  WORKS.forEach(w=>{ if(!visible[w.name])return; data[w.name].forEach(p=>{ if(!routeVisible(p.route,p.km))return; let x=xScreen(p.km),y=yRoute(p.route)-28,color=COLORS[w.name]; if(p.estadoManual==='En ejecución'){ctx.strokeStyle='rgba(255,0,0,.9)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,y,17+Math.sin(Date.now()/180)*5,0,Math.PI*2);ctx.stroke()} if(p.estadoManual==='Terminado')color='#00ff66'; ctx.fillStyle=color;ctx.strokeStyle='white';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.stroke(); drawRot(title(p.nombre),x+9,y-7,color,'left'); hits.current.push({type:'work',cls:w.name,x,y,r:13,data:p}); }); });
 };
 useEffect(()=>{draw(); const r=()=>draw(); addEventListener('resize',r); const loop=setInterval(()=>draw(),800); return()=>{removeEventListener('resize',r); clearInterval(loop)} });
 const zoomAt=(x:number,f:number)=>setS(o=>{const nz=clamp(o.z*f,CFG.zMin,CFG.zMax), wx=(x-o.pan)/o.z; return {...o,z:nz,pan:x-wx*nz}});
 const hit=(x:number,y:number)=>hits.current.find(h=>Math.hypot(x-h.x,y-h.y)<=h.r);
 const show=(e:any,h:any)=>{const el=tip.current;if(!el)return; if(!h){el.style.display='none';return} let html=''; if(h.type==='work'){const p=h.data; html=`<b style="color:${COLORS[h.cls]}">${h.cls} · ${p.route}</b><div>Trabajo: ${p.trabajo}</div><div>Km: ${fmtKm(p.kmInicial)} - ${fmtKm(p.kmFinal)}</div><div>Pistas: ${p.pistas||'-'}</div><div>Sector: ${p.sector||'-'}</div><button data-run="1" class="execToggle">${p.estadoManual}</button>`} else if(h.type==='river'){html=`<b>🌊 ${h.data.name}</b><div>${h.data.route} · km ${fmtKm(h.data.km)}</div><div>${h.data.basin}</div>`} else if(h.type==='climate'){html=`<b>Clima · ${h.data.nombre}</b><div>${h.data.txt||'cargando...'}</div>`} else {html=`<b>${h.cls} · ${h.data.route}</b><div>${h.data.nombre}</div><div>km ${fmtKm(h.data.km)}</div>`} el.innerHTML=html; el.style.display='block'; el.style.left=Math.min(innerWidth-320,e.clientX+16)+'px'; el.style.top=Math.min(innerHeight-160,e.clientY+16)+'px'; const btn=el.querySelector('[data-run]'); if(btn) btn.addEventListener('click',()=>setWorkState(h.data),{once:true}); };
 return <><canvas ref={ref} onWheel={e=>{e.preventDefault();zoomAt(e.clientX,e.deltaY<0?1.16:1/1.16)}} onMouseDown={e=>setS(o=>({...o,drag:true,lastX:e.clientX}))} onMouseUp={()=>setS(o=>({...o,drag:false}))} onMouseMove={e=>{if(s.drag)setS(o=>({...o,pan:o.pan+e.clientX-o.lastX,lastX:e.clientX})); else show(e,hit(e.clientX,e.clientY));}}/><div ref={tip} id="tooltip"/></>;
}
